---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Alternative semantic commit checker
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]

  - repo: local
    hooks:
      - id: service-codestyle
        name: service-codestyle
        entry: make service-codestyle
        language: system
        pass_filenames: false
        always_run: true

      - id: frontend-codestyle
        name: frontend-codestyle
        entry: make frontend-codestyle
        language: system
        pass_filenames: false
        always_run: true

      - id: it
        name: it
        entry: make service-codestyle frontend-codestyle
        language: system
        pass_filenames: false
        always_run: true
