# This tells OliveTin to not spawn the internal micro reverse proxy. 
#
# This gives you more fine grained control, but requires quite a bit more setup. 
# Most users will set this to "true" and use the built-in micro reverse proxy.
useSingleHTTPFrontend: false

# The WebUI is simply a static webserver. OliveTin comes with one builtin to
# make things easy, but you can also host the "webui" directory on a static 
# webserver.
#listenAddressWebUI: 0.0.0.0:1340 

# The REST API is used by the WebUI. 
#listenAddressRestActions: 0.0.0.0:1338 

# The gRPC API is unsed by the WebUI, and can also be limited to localhost:1339.
#listenAddressGrpcActions: 0.0.0.0:1339 


