# There is a built-in micro proxy that will host the webui and REST API all on 
# one port (this is called the "Single HTTP Frontend") and means you just need 
# one open port in the container/firewalls/etc. 
#
# Listen on all addresses available, port 1337
listenAddressSingleHTTPFrontend: 0.0.0.0:1337 

hideNavigation: true

# Actions (buttons) to show up on the WebUI:
actions:   
- title: Ping example.com
  shell: ping example.com -c 1
  icon: ping
