---
name: "Codestyle checks"

on:
  push:
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'webui/**'
      - 'integration-tests/**'
      - 'OliveTin.proto'


jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'
          cache: true

      - name: deps
        run: make grpc

      - name: daemon
        run: make daemon-codestyle

      - name: webui
        run: make webui-codestyle
